import Foundation

/// A single clinical consultation session held in memory for the duration
/// of the doctor's review + export cycle.
///
/// Lifecycle is owned by `SessionStore` (issue #2):
///   - Created from a completed `RecordingSession`.
///   - Mutated as the LLM produces `draftNotes`, the practitioner edits,
///     and a patient + appointment are selected.
///   - Discarded on successful export, quit, or inactivity timeout.
///
/// **PHI.** Never persisted to disk, UserDefaults, logs, or crash reports.
/// See `.claude/references/phi-handling.md`.
struct ClinicalSession: Sendable, Identifiable {
    let id: UUID

    /// The underlying transcript + audio metadata produced by the
    /// recording pipeline.
    var recordingSession: RecordingSession

    /// SOAP note generated by `ClinicalNotesProcessor` (#5). `nil` while
    /// generation is pending or if the LLM fell back to the raw
    /// transcript.
    var draftNotes: StructuredNotes?

    /// Tri-state load signal driving the ReviewScreen's UX (#100):
    /// `.pending` shows a generation overlay so the doctor never sees
    /// blank editors silently; `.ready` is the existing edit surface;
    /// `.fallback(reasonCode:)` surfaces a banner + raw-transcript
    /// affordance so a model-unavailable / empty-SOAP / invalid-JSON
    /// failure stays visible instead of degrading to "all empty".
    /// `reasonCode` is a structural sentinel (e.g. `model_unavailable`,
    /// `invalid_json_after_retry`) — never PHI.
    var draftStatus: ClinicalNotesDraftStatus

    /// Snippets from `draftNotes.excluded` that the practitioner has
    /// re-added to a SOAP section. Tracked here (not in `StructuredNotes`)
    /// so the original LLM output stays immutable for audit-trail
    /// purposes and the ReviewScreen drawer can hide re-added entries.
    var excludedReAdded: [String]

    /// Cliniko patient ID selected for export. Type-tagged as
    /// `OpaqueClinikoID` (#59) so the type system refuses anything
    /// other than a Cliniko-shaped opaque ID — no name, DOB, or
    /// free-form string can land here.
    var selectedPatientID: OpaqueClinikoID?

    /// Display name of the selected patient (e.g. "Sample Patient").
    /// Captured by the picker at selection time so the export
    /// confirmation surface (#14) can render the patient label
    /// without re-fetching from Cliniko. This is the only slot on
    /// `ClinicalSession` that holds a patient *name* — kept
    /// session-scoped, never written to disk, never logged. Cleared
    /// whenever `selectedPatientID` clears.
    var selectedPatientDisplayName: String?

    /// Cliniko appointment ID selected for export.
    var selectedAppointmentID: OpaqueClinikoID?

    init(
        id: UUID = UUID(),
        recordingSession: RecordingSession,
        draftNotes: StructuredNotes? = nil,
        draftStatus: ClinicalNotesDraftStatus = .pending,
        excludedReAdded: [String] = [],
        selectedPatientID: OpaqueClinikoID? = nil,
        selectedPatientDisplayName: String? = nil,
        selectedAppointmentID: OpaqueClinikoID? = nil
    ) {
        self.id = id
        self.recordingSession = recordingSession
        self.draftNotes = draftNotes
        self.draftStatus = draftStatus
        self.excludedReAdded = excludedReAdded
        self.selectedPatientID = selectedPatientID
        self.selectedPatientDisplayName = selectedPatientDisplayName
        self.selectedAppointmentID = selectedAppointmentID
    }
}

/// Where the SOAP draft is in its lifecycle for a single
/// `ClinicalSession`. Drives the ReviewScreen's loading overlay
/// (`.pending`) and raw-transcript fallback banner (`.fallback`).
///
/// `reasonCode` on `.fallback` is a structural sentinel matching
/// `ClinicalNotesProcessor.reasonLLMError` /
/// `.reasonInvalidJSONAfterRetry` /
/// `.reasonAllSOAPEmptyAfterRetry`, plus AppState's
/// `reasonModelUnavailable`. Never PHI — safe to log with
/// `privacy: .public`.
enum ClinicalNotesDraftStatus: Sendable, Equatable {
    /// The processor has not returned yet. ReviewScreen shows a
    /// "generating clinical note…" overlay over the SOAP editors.
    case pending
    /// `draftNotes` carries a valid LLM-produced SOAP draft. The
    /// existing edit surface renders unchanged.
    case ready
    /// The pipeline could not produce a valid draft; the doctor edits
    /// from scratch (or via "Insert raw transcript"). `reasonCode` is
    /// a structural sentinel only.
    case fallback(reasonCode: String)
}
