import Foundation

/// A single clinical consultation session held in memory for the duration
/// of the doctor's review + export cycle.
///
/// Lifecycle is owned by `SessionStore` (issue #2):
///   - Created from a completed `RecordingSession`.
///   - Mutated as the LLM produces `draftNotes`, the practitioner edits,
///     and a patient + appointment are selected.
///   - Discarded on successful export, quit, or inactivity timeout.
///
/// **PHI.** Never persisted to disk, UserDefaults, logs, or crash reports.
/// See `.claude/references/phi-handling.md`.
struct ClinicalSession: Sendable, Identifiable {
    let id: UUID

    /// The underlying transcript + audio metadata produced by the
    /// recording pipeline.
    var recordingSession: RecordingSession

    /// SOAP note generated by `ClinicalNotesProcessor` (#5). `nil` while
    /// generation is pending or if the LLM fell back to the raw
    /// transcript.
    var draftNotes: StructuredNotes?

    /// Snippets from `draftNotes.excluded` that the practitioner has
    /// re-added to a SOAP section. Tracked here (not in `StructuredNotes`)
    /// so the original LLM output stays immutable for audit-trail
    /// purposes and the ReviewScreen drawer can hide re-added entries.
    var excludedReAdded: [String]

    /// Cliniko patient ID selected for export. Opaque string; not
    /// user-visible demographics.
    var selectedPatientID: String?

    /// Cliniko appointment ID selected for export.
    var selectedAppointmentID: String?

    init(
        id: UUID = UUID(),
        recordingSession: RecordingSession,
        draftNotes: StructuredNotes? = nil,
        excludedReAdded: [String] = [],
        selectedPatientID: String? = nil,
        selectedAppointmentID: String? = nil
    ) {
        self.id = id
        self.recordingSession = recordingSession
        self.draftNotes = draftNotes
        self.excludedReAdded = excludedReAdded
        self.selectedPatientID = selectedPatientID
        self.selectedAppointmentID = selectedAppointmentID
    }
}
