// SafetyDisclaimerView.swift
// macOS Local Speech-to-Text Application
//
// One-time safety disclaimer the doctor must acknowledge before the first
// "Generate Notes" tap of a Clinical Notes Mode session (#12).
//
// Adheres to Warm Minimalism: frosted `.ultraThinMaterial`, amber accent
// from `Color+Theme.swift`, spring `(0.5, 0.7)` animation, minimal chrome,
// floating-modal aesthetic. Hosted as an overlay inside the recording
// modal — the only legitimate way to advance is the "I understand,
// continue" button. There is intentionally no close affordance, no escape
// shortcut, and no tap-to-dismiss on the disclaimer surface.

import SwiftUI

/// One-time "drafting assistant, not a diagnostic tool" disclaimer.
///
/// PHI: this view is purely presentational and never sees the transcript or
/// any patient data. The host (`LiquidGlassRecordingModal`) holds the
/// transcript and only re-enters its `handleGenerateNotes` after the
/// disclaimer is acknowledged.
struct SafetyDisclaimerView: View {
    /// Invoked when the doctor taps "I understand, continue". The host is
    /// responsible for persisting the ack flag and continuing the Clinical
    /// Notes flow.
    let onAcknowledge: () -> Void

    @State private var isVisible: Bool = false

    /// Single-shot guard so a rapid double-tap (or Return-Return) on the
    /// acknowledge button can't fire `onAcknowledge` twice. The button is
    /// also `.disabled` once flipped so the visual state matches.
    @State private var hasAcknowledged: Bool = false

    var body: some View {
        ZStack {
            // Block interaction with anything underneath. The disclaimer must
            // not be dismissable by tapping outside it (#12 AC item 2).
            Color.black.opacity(0.35)
                .ignoresSafeArea()
                .contentShape(Rectangle())
                .onTapGesture { /* absorb */ }

            disclaimerCard
                .scaleEffect(isVisible ? 1.0 : 0.92)
                .opacity(isVisible ? 1.0 : 0.0)
        }
        .onAppear {
            withAnimation(.spring(response: 0.5, dampingFraction: 0.7)) {
                isVisible = true
            }
        }
        .accessibilityIdentifier("safetyDisclaimerView")
    }

    private var disclaimerCard: some View {
        VStack(spacing: 20) {
            warningHeader

            disclaimerCopy

            acknowledgeButton
        }
        .padding(28)
        .frame(width: 380)
        .background(.ultraThinMaterial)
        .clipShape(RoundedRectangle(cornerRadius: 20, style: .continuous))
        .overlay(
            RoundedRectangle(cornerRadius: 20, style: .continuous)
                .stroke(Color.white.opacity(0.18), lineWidth: 1)
        )
        .shadow(color: .black.opacity(0.25), radius: 28, x: 0, y: 12)
    }

    private var warningHeader: some View {
        VStack(spacing: 12) {
            Image(systemName: "exclamationmark.triangle.fill")
                .font(.system(size: 40))
                .foregroundStyle(Color("AmberBright", bundle: nil))
                .accessibilityHidden(true)

            Text("This is a drafting assistant, not a diagnostic tool")
                .font(.system(size: 17, weight: .semibold, design: .rounded))
                .foregroundStyle(.primary)
                .multilineTextAlignment(.center)
                .fixedSize(horizontal: false, vertical: true)
                .accessibilityAddTraits(.isHeader)
                .accessibilityIdentifier("safetyDisclaimerView.title")
        }
    }

    private var disclaimerCopy: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text(
                "The clinical notes generated by this tool are AI-assisted drafts based on " +
                "your consultation transcript. They may contain inaccuracies, omit important " +
                "findings, or suggest techniques that are not appropriate for your patient."
            )
            .font(.system(size: 13))
            .foregroundStyle(.secondary)
            .fixedSize(horizontal: false, vertical: true)

            Text("You are responsible for reviewing, editing, and clinically validating every note before export. Do not export or rely on a note you have not reviewed.")
                .font(.system(size: 13, weight: .medium))
                .foregroundStyle(.primary)
                .fixedSize(horizontal: false, vertical: true)

            Text("By continuing you confirm you understand the above.")
                .font(.system(size: 12))
                .foregroundStyle(.secondary)
                .fixedSize(horizontal: false, vertical: true)
        }
        .accessibilityElement(children: .combine)
        .accessibilityIdentifier("safetyDisclaimerView.copy")
    }

    private var acknowledgeButton: some View {
        Button {
            guard !hasAcknowledged else { return }
            hasAcknowledged = true
            onAcknowledge()
        } label: {
            Text("I understand, continue")
                .font(.system(size: 14, weight: .semibold, design: .rounded))
                .frame(maxWidth: .infinity)
                .padding(.vertical, 6)
        }
        .buttonStyle(.borderedProminent)
        .tint(Color("AmberPrimary", bundle: nil))
        .keyboardShortcut(.return)
        .disabled(hasAcknowledged)
        .accessibilityIdentifier("safetyDisclaimerView.acknowledgeButton")
    }
}

// MARK: - Previews

#Preview("Safety Disclaimer") {
    ZStack {
        Color.gray.opacity(0.4)
        SafetyDisclaimerView(onAcknowledge: {})
    }
    .frame(width: 480, height: 480)
    .preferredColorScheme(.light)
}

#Preview("Safety Disclaimer · Dark") {
    ZStack {
        Color.black.opacity(0.6)
        SafetyDisclaimerView(onAcknowledge: {})
    }
    .frame(width: 480, height: 480)
    .preferredColorScheme(.dark)
}
